### ISSUE TITLE
jekyll build errors: undefined method `tainted?'

### ISSUE THREAD

**Issue by asiryk** [neovim/neovim.github.io#314]
I'm trying to set up the project locally. I follow the instructions in readme, but the jekyll serve command fails.

I run it inside docker container using 

```dockerfile
FROM ruby
RUN gem install bundler
WORKDIR /site
COPY ["Gemfile", "Gemfile.lock", "./"]
RUN bundle config set --local path .bundle
RUN bundle install
COPY . .
EXPOSE 4000
CMD ["bundle", "exec", "jekyll", "serve"]
```

```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Configuration file: /site/_config.yml
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
            Source: /site
       Destination: /site/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
  Liquid Exception: undefined method `tainted?' for "Back Neovim Through Bountysource":String in /_layouts/post.html
jekyll 3.9.2 | Error:  undefined method `tainted?' for "Back Neovim Through Bountysource":String
/site/.bundle/ruby/3.2.0/gems/liquid-4.0.3/lib/liquid/variable.rb:124:in `taint_check': undefined method `tainted?' for "Back Neovim Through Bountysource":String (NoMethodError)

      return unless obj.tainted?
                       ^^^^^^^^^
	from /site/.bundle/ruby/3.2.0/gems/liquid-4.0.3/lib/liquid/variable.rb:89:in `render'
	from /site/.bundle/ruby/3.2.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
	from /site/.bundle/ruby/3.2.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:80:in `render'
	from /site/.bundle/ruby/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
	from /site/.bundle/ruby/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
	from /site/.bundle/ruby/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
	from /site/.bundle/ruby/3.2.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:126:in `render_liquid'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:195:in `render_layout'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:158:in `place_in_layouts'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:88:in `render_document'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:62:in `run'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:479:in `render_regenerated'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:464:in `block (2 levels) in render_docs'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:463:in `each'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:463:in `block in render_docs'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:462:in `each_value'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:462:in `render_docs'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:191:in `render'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/site.rb:71:in `process'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/command.rb:28:in `process_site'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:65:in `build'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:36:in `process'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `block in start'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `each'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `start'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
	from /site/.bundle/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /site/.bundle/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /site/.bundle/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /site/.bundle/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /site/.bundle/ruby/3.2.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /site/.bundle/ruby/3.2.0/gems/jekyll-3.9.2/exe/jekyll:15:in `<top (required)>'
	from /site/.bundle/ruby/3.2.0/bin/jekyll:25:in `load'
	from /site/.bundle/ruby/3.2.0/bin/jekyll:25:in `<top (required)>'
	from /site/.bundle/ruby/3.2.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `load'
	from /site/.bundle/ruby/3.2.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `kernel_load'
	from /site/.bundle/ruby/3.2.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:28:in `run'
	from /site/.bundle/ruby/3.2.0/gems/bundler-2.2.16/lib/bundler/cli.rb:494:in `exec'
	from /site/.bundle/ruby/3.2.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /site/.bundle/ruby/3.2.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /site/.bundle/ruby/3.2.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /site/.bundle/ruby/3.2.0/gems/bundler-2.2.16/lib/bundler/cli.rb:30:in `dispatch'
	from /site/.bundle/ruby/3.2.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /site/.bundle/ruby/3.2.0/gems/bundler-2.2.16/lib/bundler/cli.rb:24:in `start'
	from /site/.bundle/ruby/3.2.0/gems/bundler-2.2.16/exe/bundle:49:in `block in <top (required)>'
	from /site/.bundle/ruby/3.2.0/gems/bundler-2.2.16/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	from /site/.bundle/ruby/3.2.0/gems/bundler-2.2.16/exe/bundle:37:in `<top (required)>'
	from /usr/local/bundle/bin/bundle:25:in `load'
	from /usr/local/bundle/bin/bundle:25:in `<main>'

```

**Comment by justinmk** [comment]
maybe the gem lock needs an update. it has been awhile since the deps were updated. help appreciated

**Comment by teto** [comment]
if you have nix installed (a longshot I know), you can run `nix-shell` and the commands then work (I've just tested).

**Comment by justinmk** [comment]
fixed with https://github.com/neovim/neovim.github.io/commit/d73858f621abeeabc83d09dfb62aec0b1f0d5a25

note that the ruby version can matter a lot, I'm using `ruby 3.2.2`
